### ISSUE TITLE
Axios version allows SSRF via unexpected behavior where requests for path relative URLs get processed as protocol relative URLs.

### ISSUE THREAD

**Issue by jamesRRL** [prismatic-io/spectral#272]
This package relies on Axios 1.6.2 which has a bug that was patched in 1.7.4 that allows server side request forgery

**Comment by taylorreece** [comment]
Hey @jamesRRL - are you on the latest version of Spectral? It looks like we patched that in `@prismatic-io/spectral` version `9.1.2` https://github.com/prismatic-io/spectral/pull/262
<img width="668" alt="image" src="https://github.com/user-attachments/assets/914d75ca-9758-4e1c-91c5-8e4f28bef60e">

**Comment by jamesRRL** [comment]
@taylorreece thanks for the quick reply here! our reliance on spectral stems from the installation of the latest version of `prismatic-io/prism` (v1.7.2), do you know if that package will be upgraded in line with this one to use the latest spectral version?

**Comment by taylorreece** [comment]
Hey @jamesRRL , the latest version of prism, `@prismatic-io/prism@7.1.4`, now relies on the latest spectral, which depends on a patched version of `axios`.
